/*
 * This Scala Testsuite was generated by the Gradle 'init' task.
 */
package taller

import org.junit.runner.RunWith
import org.scalatest.funsuite.AnyFunSuite
import org.scalatestplus.junit.JUnitRunner
import taller.RiegoOptimo._

@RunWith(classOf[JUnitRunner])
class costoRiegoFincaParTest extends AnyFunSuite {

  val finca : Finca = Vector(
    (10, 3, 4),
    (5, 3, 3),
    (2, 2, 1),
    (8, 1, 1),
    (6, 4, 2)
  )
  val progRiego1 : ProgRiego = Vector(0,1,4,2,3)
  val progRiego2 : ProgRiego = Vector(2,1,4,3,0)

  test("costoRiegoFinca pi1 secuencial") {
    assert(costoRiegoFinca(finca, progRiego1) == 33)
  }

  test("costoRiegoFinca pi2 secuencial") {
    assert(costoRiegoFinca(finca, progRiego2) == 20)
  }

  test("costoRiegoFincaPar pi1 paralelo"){
    assert(costoRiegoFincaPar(finca, progRiego1) == 33)
  }

  test("costoRiegoFincaPar pi2 paralelo"){
    assert(costoRiegoFincaPar(finca, progRiego2) == 20)
  }

}
