/*
 * This Scala Testsuite was generated by the Gradle 'init' task.
 */
package taller

import org.junit.runner.RunWith
import org.scalatest.funsuite.AnyFunSuite
import org.scalatestplus.junit.JUnitRunner
import taller.RiegoOptimo._

@RunWith(classOf[JUnitRunner])
class GenerarProgramacionRiegoParTest extends AnyFunSuite {


  test("riego de finca con 3 tablones paralelo"){
    val tabFinca : Finca = fincaAlAzar(3)
    val progEsperada : Vector[ProgRiego] = Vector(
      Vector(0,1,2), Vector(0,2,1), Vector(1,0,2), Vector(1,2,0), Vector(2,1,0), Vector(2,0,1)
    )
    val progGenerada : Vector[ProgRiego] = generarProgramacionesRiegoPar(tabFinca)
    assert(progEsperada.length == progGenerada.length)
    assert(progGenerada.forall(progEsperada.toSet.contains))
  }


  test("riego de finca con 4 tablones paralelo"){
    val tabFinca : Finca = fincaAlAzar(4)
    val progEsperada : Vector[ProgRiego] = Vector(
      Vector(0, 1, 2, 3), Vector(0, 1, 3, 2), Vector(0, 2, 1, 3), Vector(0, 2, 3, 1), Vector(0, 3, 1, 2), Vector(0, 3, 2, 1),
      Vector(1, 0, 2, 3), Vector(1, 0, 3, 2), Vector(1, 2, 0, 3), Vector(1, 2, 3, 0), Vector(1, 3, 0, 2), Vector(1, 3, 2, 0),
      Vector(2, 0, 1, 3), Vector(2, 0, 3, 1), Vector(2, 1, 0, 3), Vector(2, 1, 3, 0), Vector(2, 3, 0, 1), Vector(2, 3, 1, 0),
      Vector(3, 0, 1, 2), Vector(3, 0, 2, 1), Vector(3, 1, 0, 2), Vector(3, 1, 2, 0), Vector(3, 2, 0, 1), Vector(3, 2, 1, 0)
    )
    val progGenerada : Vector[ProgRiego] = generarProgramacionesRiegoPar(tabFinca)
    assert(progEsperada.length == progGenerada.length)
    assert(progGenerada.forall(progEsperada.toSet.contains))
  }


  test("riego de finca con 5 tablones paralelo"){
    val tabFinca : Finca = fincaAlAzar(5)
    val progEsperada : Vector[ProgRiego] =
      Vector(
        Vector(0, 1, 2, 3, 4), Vector(0, 1, 2, 4, 3), Vector(0, 1, 3, 2, 4), Vector(0, 1, 3, 4, 2), Vector(0, 1, 4, 2, 3), Vector(0, 1, 4, 3, 2), Vector(0, 2, 1, 3, 4), Vector(0, 2, 1, 4, 3), Vector(0, 2, 3, 1, 4), Vector(0, 2, 3, 4, 1), Vector(0, 2, 4, 1, 3), Vector(0, 2, 4, 3, 1), Vector(0, 3, 1, 2, 4), Vector(0, 3, 1, 4, 2), Vector(0, 3, 2, 1, 4), Vector(0, 3, 2, 4, 1), Vector(0, 3, 4, 1, 2), Vector(0, 3, 4, 2, 1), Vector(0, 4, 1, 2, 3), Vector(0, 4, 1, 3, 2), Vector(0, 4, 2, 1, 3), Vector(0, 4, 2, 3, 1), Vector(0, 4, 3, 1, 2), Vector(0, 4, 3, 2, 1),
        Vector(1, 0, 2, 3, 4), Vector(1, 0, 2, 4, 3), Vector(1, 0, 3, 2, 4), Vector(1, 0, 3, 4, 2), Vector(1, 0, 4, 2, 3), Vector(1, 0, 4, 3, 2), Vector(1, 2, 0, 3, 4), Vector(1, 2, 0, 4, 3), Vector(1, 2, 3, 0, 4), Vector(1, 2, 3, 4, 0), Vector(1, 2, 4, 0, 3), Vector(1, 2, 4, 3, 0), Vector(1, 3, 0, 2, 4), Vector(1, 3, 0, 4, 2), Vector(1, 3, 2, 0, 4), Vector(1, 3, 2, 4, 0), Vector(1, 3, 4, 0, 2), Vector(1, 3, 4, 2, 0), Vector(1, 4, 0, 2, 3), Vector(1, 4, 0, 3, 2), Vector(1, 4, 2, 0, 3), Vector(1, 4, 2, 3, 0), Vector(1, 4, 3, 0, 2), Vector(1, 4, 3, 2, 0),
        Vector(2, 0, 1, 3, 4), Vector(2, 0, 1, 4, 3), Vector(2, 0, 3, 1, 4), Vector(2, 0, 3, 4, 1), Vector(2, 0, 4, 1, 3), Vector(2, 0, 4, 3, 1), Vector(2, 1, 0, 3, 4), Vector(2, 1, 0, 4, 3), Vector(2, 1, 3, 0, 4), Vector(2, 1, 3, 4, 0), Vector(2, 1, 4, 0, 3), Vector(2, 1, 4, 3, 0), Vector(2, 3, 0, 1, 4), Vector(2, 3, 0, 4, 1), Vector(2, 3, 1, 0, 4), Vector(2, 3, 1, 4, 0), Vector(2, 3, 4, 0, 1), Vector(2, 3, 4, 1, 0), Vector(2, 4, 0, 1, 3), Vector(2, 4, 0, 3, 1), Vector(2, 4, 1, 0, 3), Vector(2, 4, 1, 3, 0), Vector(2, 4, 3, 0, 1), Vector(2, 4, 3, 1, 0),
        Vector(3, 0, 1, 2, 4), Vector(3, 0, 1, 4, 2), Vector(3, 0, 2, 1, 4), Vector(3, 0, 2, 4, 1), Vector(3, 0, 4, 1, 2), Vector(3, 0, 4, 2, 1), Vector(3, 1, 0, 2, 4), Vector(3, 1, 0, 4, 2), Vector(3, 1, 2, 0, 4), Vector(3, 1, 2, 4, 0), Vector(3, 1, 4, 0, 2), Vector(3, 1, 4, 2, 0), Vector(3, 2, 0, 1, 4), Vector(3, 2, 0, 4, 1), Vector(3, 2, 1, 0, 4), Vector(3, 2, 1, 4, 0), Vector(3, 2, 4, 0, 1), Vector(3, 2, 4, 1, 0), Vector(3, 4, 0, 1, 2), Vector(3, 4, 0, 2, 1), Vector(3, 4, 1, 0, 2), Vector(3, 4, 1, 2, 0), Vector(3, 4, 2, 0, 1), Vector(3, 4, 2, 1, 0),
        Vector(4, 0, 1, 2, 3), Vector(4, 0, 1, 3, 2), Vector(4, 0, 2, 1, 3), Vector(4, 0, 2, 3, 1), Vector(4, 0, 3, 1, 2), Vector(4, 0, 3, 2, 1), Vector(4, 1, 0, 2, 3), Vector(4, 1, 0, 3, 2), Vector(4, 1, 2, 0, 3), Vector(4, 1, 2, 3, 0), Vector(4, 1, 3, 0, 2), Vector(4, 1, 3, 2, 0), Vector(4, 2, 0, 1, 3), Vector(4, 2, 0, 3, 1), Vector(4, 2, 1, 0, 3), Vector(4, 2, 1, 3, 0), Vector(4, 2, 3, 0, 1), Vector(4, 2, 3, 1, 0), Vector(4, 3, 0, 1, 2), Vector(4, 3, 0, 2, 1), Vector(4, 3, 1, 0, 2), Vector(4, 3, 1, 2, 0), Vector(4, 3, 2, 0, 1), Vector(4, 3, 2, 1, 0))
    val progGenerada : Vector[ProgRiego] = generarProgramacionesRiegoPar(tabFinca)
    assert(progEsperada.length == progGenerada.length)
    assert(progGenerada.forall(progEsperada.toSet.contains))
  }
}
